### ISSUE TITLE
Adding word for a specific language

### ISSUE THREAD

**Issue by PierreMarchand20** [Jason-Rev/vscode-spell-checker#323]
Is it possible to add a new word, but only for a specific language ? For example, I have `en` and `fr` enabled. So when I add a English word, how can I specify that it is only for `en` ?

**Comment by Jason3S** [comment]
It is possible to manually do it, but not yet with a command.

```
"cSpell.languageSettings": [
    {
        "local": "en",
        "words": ["running"]
    },
    {
        "local": "fr",
        "words": ["avoir"]
    }
],
```

**Comment by ncovercash** [comment]
I'd love this as a command!  LaTeX, in particular, has a ton of funky stuff, like `renewcommand`, `textbf`, `lfoot`, etc that I certainly don't want to add workspace or user-wide (as I'd certainly manage to screw myself up there).

The workaround you listed works for now, but it's a bit annoying to have to go manually whitelist each one.

**Comment by Jason3S** [comment]
@ncovercash,

I suggest making a custom dictionary file for LaTeX files:

**`cspell.json`**

```js
{
    "dictionaryDefinitions": [
        {
            "name": "LaTeX Words",
            "path": "./cspell-latex-dict.txt",
            "description": "LaTex Dictionary",
            "addWords": true
        }
    ],
    "languageSettings": [
        {
            "languageId": "latex",
            "dictionaries": [ "LaTeX Words"]
        }
    ]
}
```

**`cspell.yaml`**

```yaml
dictionaryDefinitions:
  - name: "LaTeX Words"
    path: "./cspell-latex-dict.txt"
    description: "LaTex Dictionary"
    addWords: true
languageSettings:
  - languageId: "latex"
    dictionaries:
      - "LaTeX Words"
```

It will show up something like this:
![image](https://user-images.githubusercontent.com/3740137/150332831-c98d14a0-2f1d-46f9-ad1e-b2862a03e9c1.png)

You will need to create the `.cspell-latex-dict.txt` file for it to work.
